common_official:
  - niri
  - kitty
  - zellij
  - yazi
  - rmpc
  - mpd
  - mpv
  - nsxiv
  - gimp
  - qutebrowser
  - nushell
  - starship
  - zoxide
  - ripgrep
  - btop
  - duf
  - ncdu
  - bat
  - vlc
  - feh
  - pcmanfm
  - vesktop-bin
  - zathura
  - git
  - lazygit
  - github-cli
  - obsidian
  - matugen

common_aur:
  - neovim-nightly-bin
  - zen-browser-bin
  - noctalia-git
  - bunjs-bin
  - carapace-bin
  - emmet-language-server
  - fish-lsp
  - localsend-bin
  - mpdris2-git
  - music-presence-bin
  - nodejs-emmet-ls
  - pipes-rs
  - sesh-bin
  - sptlrx
  - zenmonitor3

git_repos:
  - repo: "https://github.com/ulfurloyd/phoenyx-wallpapers"
    dest: "{{ ansible_env.HOME }}/Wallpapers"
  - repo: "https://github.com/ulfurloyd/phoenyxlab"
    dest: "{{ ansible_env.HOME }}/Projects/phoenyxlab"
