#+title: phoenyx
#+author: ulfurloyd

* Table of Contents :toc:
- [[#why-im-back-on-arch][Why I'm back on Arch]]
- [[#ansible][Ansible]]
  - [[#features-so-far][Features So Far]]
- [[#directory-overview][Directory Overview]]

* Why I'm back on Arch
Spent close to a year in NixOS. It was honestly a lot of fun, Nix is a cool playground to learn new tools and build a deep configuration.

But over time, I've also noticed growing pains that come with using Nix(OS) as your daily driver desktop distro.

Issues mainly stemming from it not respecting traditional Linux FHS standards, software needing to be configured in a blend of home-manager
and classic configuration formats, config changes not reflecting until you rebuild your system or HM config, and more.

As it turns out, Arch Linux has a way to be enticing enough that you never truly escape it :3

* Ansible
Ansible is a system/configuration management and automation software. I'm working on integrating it into my dotfiles for easy reproducibility, à la NixOS.
** Features So Far
*** Package Management
Installs required packages using:
**** `pacman` for official Arch packages (via the base role)
**** `paru` and [[https://github.com/kewlfft/ansible-aur][kewlfft.aur]] Ansible module for AUR packages (via the aur role)
*** Host-Specific Package Lists
**** Variables for packages are stored in `vars/common.yml`, `vars/nyx.yml`, and `vars/lykaon.yml` to separate common and per-machine packages.
**** Hostname of the current machine is detected automatically via `ansible_hostname`.
*** User Setup
**** Creates an `aur_builder` that does all the AUR installation.
**** Configures sudo permissions for that user without password for `pacman`.
*** Dotfiles & Emacs Config
**** Dotfiles (managed via Chezmoi) are included and applied post-install.
**** Emacs is installed via `base`, and my Emacs configuration is pulled into `~/.config/emacs` using a dedicated `emacs` role.

* Directory Overview
#+BEGIN_SRC
~/.local/share/chezmoi/
├── ansible/
│   ├── roles/
│   │   ├── base/     # installs pacman packages
│   │   ├── aur/      # installs paru and AUR packages
│   │   └── emacs/    # pulls Emacs config
│   ├── vars/
│   │   ├── common.yml
│   │   ├── nyx.yml
│   │   └── lykaon.yml
│   └── playbook.yml
└── dot_config (chezmoi-managed config)
#+END_SRC
