[theme.templates]
builtin_ids = [
	"btop",
	"gtk3",
	"gtk4",
	"hyprland",
	"kcolorscheme",
	"kitty",
	"niri",
	"qt",
	"starship",
	"umbriel",
]
community_ids = [
	"opencode",
	"pywalfox",
	"qutebrowser",
	"zen-browser",
	"discord",
	"gimp",
	"neovim",
	"obsidian",
	"heroiclauncher",
	"steam",
	"fastfetch",
	"zathura",
	"zellij",
	"hyprtoolkit",
	"bat",
	"lazygit",
	"yazi",
]

[theme.templates.user.alacritty]
input_path = "~/.config/matugen/colors-alacritty.kdl"
output_path = "~/.config/alacritty/colors.toml"

[theme.templates.user.cava]
input_path = "~/.config/matugen/colors-cava.ini"
output_path = "~/.config/cava/themes/matugen"
post_hook = "pkill -USR1 cava"

[theme.templates.user.obs]
input_path = "~/.config/matugen/colors-obs.obt"
output_path = "~/.config/obs-studio/themes/matugen.obt"

[theme.templates.user.obsidian]
input_path = "~/.config/matugen/colors-obsidian.css"
output_path = "~/Documents/phoenyx/.obsidian/snippets/matugen.css"

[theme.templates.user.pywalfox]
input_path = "~/.config/matugen/colors-pywalfox.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"

[theme.templates.user.qutebrowser]
input_path = "~/.config/matugen/colors-qutebrowser.py"
output_path = "~/.config/qutebrowser/matugen.py"

[theme.templates.user.rmpc]
input_path = "~/.config/matugen/colors-rmpc.ron"
output_path = "~/.config/rmpc/themes/matugen.ron"

[theme.templates.user.starship]
input_path = "~/.config/matugen/colors-starship.toml"
output_path = "~/.config/starship.toml"

[theme.templates.user.terminal-sequences]
input_path = "~/.config/matugen/sequences"
output_path = "~/.cache/terminal-sequences"
post_hook = "cat ~/.cache/terminal-sequences > /dev/pts/[0-9]*"

[theme.templates.user.tmux]
input_path = "~/.config/matugen/colors-tmux.conf"
output_path = "~/.config/tmux/generated.conf"
post_hook = "tmux source-file ~/.config/tmux/generated.conf"

[theme.templates.user.vesktop]
input_path = "~/.config/matugen/colors-vesktop.css"
output_path = "~/.config/vesktop/themes/midnight-discord.css"

[theme.templates.user.wezterm]
input_path = "~/.config/matugen/colors-wezterm.toml"
output_path = "~/.config/wezterm/colors/matugen_theme.toml"
post_hook = "touch ~/.config/wezterm/wezterm.lua"

[theme.templates.user.yazi]
input_path = "~/.config/matugen/colors-yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[theme.templates.user.zathura]
input_path = "~/.config/matugen/colors-zathura"
output_path = "~/.config/zathura/zathurarc"

[theme.templates.user.zed]
input_path = "~/.config/matugen/colors-zed.json"
output_path = "~/.config/zed/themes/matugen.json"

[theme.templates.user.zellij]
input_path = "~/.config/matugen/colors-zellij.kdl"
output_path = "~/.config/zellij/themes/matugen.kdl"
post_hook = "~/.local/bin/noctalia_fix_zellij.sh"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/wolf/Wallpapers"
transition = ["disc", "fade", "stripes", "wipe", "zoom"]
transition_on_startup = true

[backdrop]
enabled = true
