[audio]
enable_sounds = true

[calendar]
enabled = true

[calendar.account.personal_google]
name = "calendar"
type = "google"

[control_center]
hidden_tabs = ["monitor", "power", "network", "bluetooth", "screen-time"]
width = 900

[dock]
enabled = false

[keybinds]
cancel = ["Escape"]
down = ["Ctrl+n", "Ctrl+j"]
left = ["Ctrl+h"]
right = ["Ctrl+l"]
up = ["Ctrl+p", "Ctrl+k"]
validate = ["Return"]

[location]
auto_locate = true

[notification]
background_opacity = 0.4
layer = "overlay"

[osd]
background_opacity = 0.40000000000000002
position = "bottom_center"

[system.monitor]
gpu_poll_seconds = 5
