[audio]
enable_sounds = true

[dock]
enabled = false

[keybinds]
cancel = ["Escape"]
down = ["Ctrl+n"]
left = ["Ctrl+h"]
right = ["Ctrl+l"]
up = ["Ctrl+p"]
validate = ["Return"]

[notification]
background_opacity = 0.4

[osd]
position = "bottom_center"

[weather]
auto_locate = true
