[audio]
enable_sounds = true

[dock]
enabled = false

[keybinds]
cancel = ["Escape"]
down = ["Ctrl+n"]
left = ["Ctrl+h"]
right = ["Ctrl+l"]
up = ["Ctrl+p"]
validate = ["Return"]

[location]
auto_locate = true

[notification]
background_opacity = 0.4

[osd]
background_opacity = 0.40000000000000002
position = "bottom_center"
