[plugins]
enabled = ["noctalia/translator", "noctalia/screen_recorder"]

[plugin_settings."noctalia/screen_recorder"]
video_source = "portal"

[plugin_settings."noctalia/wallhaven"]
download_dir = ""

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"
