[plugins]
enabled = []

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"
