host_official:
  - obs-studio
  - beets
  - picard
  - gamemode
  - docker
  - kubectl
  - k9s
  - helm
  - aws-cli-v2
  - pass
  - age
  - sops
host_aur:
  - proton-cachyos-slr
  - protonup-qt
  - lrcget-bin
  - quickemu-git
  - quickgui-bin
  - vercel
