- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory
    mode: '0700'

- name: Copy SSH private key (vault encrypted)
  ansible.builtin.copy:
    src: id_ed25519.vault
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
    mode: '0600'

- name: Copy SSH public key (vault encrypted)
  ansible.builtin.copy:
    src: id_ed25519.pub.vault
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519.pub"
    mode: '0644'

- name: Ensure GitHub is in known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com') }}"
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    state: present

- name: Check if private key exists at expected path
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
  register: ssh_key_debug

- name: Show result of key existence check
  ansible.builtin.debug:
    msg: "SSH key exists at {{ dotfiles_user_home }}/.ssh/id_ed25519: {{ ssh_key_debug.stat.exists }}"
