- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"

- name: Copy SSH private key (vault encrypted)
  copy: 
    src: id_ed25519.vault
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
    mode: '0600'
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"

- name: Copy SSH public key (vault encrypted)
  copy:
    src: id_ed25519.pub.vault
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519.pub"
    mode: '0644'
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"

- name: Ensure GitHub is in known_hosts
  known_hosts:
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com') }}"
    state: present
