- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory
    mode: '0700'
  when: not ansible_check_mode

- name: Copy SSH private key from vault variable
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
    mode: '0600'
  when: not ansible_check_mode

- name: Copy SSH public key from vault variable
  ansible.builtin.copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ dotfiles_user_home }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: not ansible_check_mode

- name: Wait a moment after copying key
  ansible.builtin.pause:
    seconds: 1
  when: not ansible_check_mode
