- name: Ensure chezmoi is installed
  community.general.pacman:
    name: chezmoi
    state: present
  become: true

- name: Initialize chezmoi if not already initialized
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/chezmoi"
  register: chezmoi_initialized

- name: Init chezmoi with existing repo
  ansible.builtin.command:
    cmd: chezmoi init --source ~/.local/share/chezmoi
  when: not chezmoi_initialized.stat.exists
  changed_when: true

- name: Apply chezmoi config
  ansible.builtin.command:
    cmd: chezmoi apply --force
  become: false
  changed_when: true
  check_mode: no
  when: ansible_env.CI is not defined
