# move statusbar to top
set-option -g status-position top

# reload config inplace
bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

# set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# enable mouse support
set -g mouse on

# stop renaming windows automatically
set-option -g allow-rename off

# set base index to be 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# split panes with | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# use vim keybindings in copy mode
setw -g mode-keys vi

# increase scrollback buffer
set -g history-limit 10000

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

# run tpm
run '~/.config/tmux/plugins/tpm/tpm'
