# move statusbar to top
set-option -g status-position top

# reload config inplace
bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

# set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# enable mouse support
set -g mouse on

# skip "kill-pane 1? (y/n)" prompt
bind-key x kill-pane

set -g allow-passthrough on

# don't exit from tmux when closing a session
set -g detach-on-destroy off

# stop renaming windows automatically
set-option -g allow-rename off

# set base index to be 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# split panes with | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# use vim keybindings in copy mode
setw -g mode-keys vi

# increase scrollback buffer
set -g history-limit 10000

# sesh stuff
bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

bind -N "last-session (via sesh) " L run-shell "sesh last"

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'schasse/tmux-jump'

# Set color defaults
set -g status-bg                          "#130d07"
set -gq @thm_bar_bg                       "#130d07"

set -gq @thm_bg                           "#18120c"
set -gq @thm_fg                           "#eee0d5"
set -gq @thm_primary                      "#f9ba72"
set -gq @thm_inverse_primary              "#835414"
set -gq @thm_surface_low                  "#211a13"
set -gq @thm_surface                      "#251e17"
set -gq @thm_surface_variant              "#302921"
set -gq @thm_outline                      "#50453a"
set -gq @thm_text_variant                 "#d4c4b5"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"

source-file ~/.config/tmux/generated.conf

# run tpm
run '~/.config/tmux/plugins/tpm/tpm'
