#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

blacklist = ["scratch"]

[[session]]
name = "based"
path = "~"
windows = [ "obsidian" ]

[[window]]
name = "obsidian"
startup_script = "nvim"
path = "~/Documents/phoenyx"

[[session]]
name = "docker"
path = "~/Dev/Docker/phoenyx-media"
startup_command = "git status"
windows = [ "dash" ]

[[window]]
name = "dash"
startup_script = "dockedup"

[[session]]
name = "music"
path = "~"
startup_command = "rmpc"

[[session]]
name = "configs"
path = "~/.local/share/chezmoi"
startup_command = "git status"
