- name: Configure Arch Systems with host-specific packages
  hosts: localhost
  connection: local
  become: false

  vars:
    dotfiles_user: "wolf"
    dotfiles_user_home: "{{ lookup('env', 'HOME') }}"
    aur_user: "{{ 'ansible' if ansible_env.CI is defined else 'aur_builder' }}"

  vars_files:
    - roles/aur/vars/common.yml
    - roles/aur/vars/{{ ansible_hostname }}.yml

  roles:
    - pre
    - ssh
    - base
    - aur
    - emacs
    - chezmoi
    - wallpapers
