- name: Configure Arch Systems with host-specific packages
  hosts: localhost
  connection: local
  become: true

  vars:
    aur_user: "{{ ansible_user_id if ansible_env.CI is defined else 'aur_builder' }}"
    dotfiles_user: "wolf"
    dotfiles_user_home: "/home/wolf"

  vars_files:
    - roles/aur/vars/common.yml
    - roles/aur/vars/{{ ansible_hostname }}.yml

  roles:
    - pre
    - ssh
    - base
    - aur
    - emacs
    - chezmoi
    - wallpapers
