- name: Configure Arch Systems with host-specific packages
  hosts: localhost
  connection: local
  become: yes

  vars_files:
    - roles/aur/vars/common.yml
    - roles/aur/vars/{{ ansible_hostname }}.yml

  roles:
    - base
    - aur
    - emacs
