- name: Configure phoenyx system
  hosts: localhost
  connection: local
  become: false

  vars_files:
    - values.yml
    - group_vars/all.yml
    - group_vars/{{ ansible_hostname }}.yml

  roles:
    - base
    - dwm
