- name: Configure Arch Systems with host-specific packages
  hosts: localhost
  connection: local
  become: false

  vars:
    aur_user: "{{ 'ansible' if ansible_env.CI is defined else 'aur_builder' }}"
    # aur_user: >-
    #   {{ 'ansible' if ansible_env.CI is defined else 'aur_builder' }}
    # aur_user: "{{ ansible_user_id if ansible_env.CI is defined else 'aur_builder' }}"
    dotfiles_user: "wolf"
    dotfiles_user_home: "{{ lookup('env', 'HOME') }}"

  vars_files:
    - roles/aur/vars/common.yml
    - roles/aur/vars/{{ ansible_hostname }}.yml

  roles:
    - pre
    - ssh
    - base
    - aur
    - emacs
    - chezmoi
    - wallpapers
