- name: Ensure git is present on the system
  community.general.pacman:
    name: git
    state: present

- name: Clone emacs config repo
  ansible.builtin.git:
    repo: https://github.com/ulfurloyd/wolf-emacs.git
    dest: "{{ dotfiles_user_home }}/.config/emacs"
    version: main
    force: false
    update: true
