- name: Ensure git is present on the system
  community.general.pacman:
    name: git
    state: present

- name: Ensure SSH private key exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
  register: ssh_key

# - name: Fail if SSH key is missing
#   ansible.builtin.fail:
#     msg: "SSH key not found at ~/.ssh/id_ed25519"
#   when: not ssh_key.stat.exists
#
- name: Ensure git is a known host
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    state: present
    # exclusive: false

- name: Clone emacs config repo
  ansible.builtin.git:
    repo: git@github.com:ulfurloyd/wolf-emacs.git
    dest: "{{ dotfiles_user_home }}/.config/emacs"
    version: main
    force: false
    update: true
  become: false
