- name: Ensure git is present on the system
  pacman:
    name: git
    state: present

- name: Clone emacs config repo
  git:
    repo: https://github.com/ulfurloyd/wolf-emacs.git
    dest: "{{ ansible_user_dir }}/.config/emacs"
    version: main
    force: yes
    update: yes
