- name: Clone emacs config repo
  ansible.builtin.git:
    repo: git@github.com:ulfurloyd/wolf-emacs.git
    dest: "{{ dotfiles_user_home }}/.config/emacs"
    version: main
    force: false
    update: true
  become: false
