- name: Ensure git is present on the system
  community.general.pacman:
    name: git
    state: present

- name: Ensure SSH private key exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.ssh/id_ed25519"
  register: ssh_key
  become: false
  when: not ansible_check_mode

- name: Ensure git is a known host
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    state: present
  when: not ansible_check_mode

- name: Clone emacs config repo
  ansible.builtin.git:
    repo: git@github.com:ulfurloyd/wolf-emacs.git
    dest: "{{ dotfiles_user_home }}/.config/emacs"
    version: main
    force: false
    update: true
  become: false
  when: not ansible_check_mode
