- name: Merge common and host-specific AUR package lists
  set_fact:
    aur_packages: "{{ aur_common_packages + aur_host_packages }} | default([]) }}"

- name: Create the 'aur_builder' user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the 'aur_builder' user to run 'sudo pacman without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: visudo -cf '%s'

- name: Install paru
  become_user: aur_builder
  shell: |
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
  args:
    creates: /usr/bin/paru

- name: Install AUR packages
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    use: paru
    name: "{{ item }}"
  loop: "{{ aur_packages }}"
