- name: Ensure pywal16 is installed
  kewlfft.aur.aur:
    name: python-pywal16
    use: paru
    state: present
  become: true
  become_user: "{{ aur_user }}"
  when: aur_user != ansible_user_id

- name: Ensure ~/Wallpapers directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/Wallpapers"
    state: directory
    mode: '0755'

- name: Clone the wallpapers repo if not present
  ansible.builtin.git:
    repo: "https://github.com/ulfurloyd/phoenyx-wallpapers.git"
    dest: "{{ dotfiles_user_home }}/Wallpapers"
    version: main
    update: false
