# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 2000
scan_timeout = 10

format = '$directory$git_branch $git_metrics$fill$time$line_break$character'

[package]
disabled = true

[fill]
disabled = false
symbol = " "

[character]
success_symbol = "❯"
error_symbol = "❯"

[git_branch]
symbol = 'on '
format = '$symbol$branch'

[git_metrics]
disabled = false

[time]
disabled = false
time_format = '%H:%M:%S'
