name: Ansible Lint & Dry-Run

on:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-check.yml'
  pull_request:

jobs:
  dry-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host: [nyx, lykaon]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          pip install ansible-lint
          ansible-galaxy collection install kewlfft.aur

      - name: Run ansible-lint
        run: |
          ansible-lint ansible/playbook.yml

      - name: "Run dry-run for host: ${{ matrix.host }}"
        run: |
          ansible-playbook ansible/playbook.yml \
            -i localhost, \
            --connection=local \
            --check \
            -e ansible_hostname=${{ matrix.host }}
