# name: Ansible Lint & Dry-Run
# 
# on:
#   push:
#     paths:
#       - 'ansible/**'
#       - '.github/workflows/ansible-check.yml'
#   pull_request:
# 
# jobs:
#   dry-run:
#     runs-on: ubuntu-latest
#     container:
#       image: archlinux:latest
# 
#     strategy:
#       matrix:
#         host: [nyx, lykaon]
# 
#     steps:
#       - name: Install dependencies and create ansible user
#         run: |
#           pacman -Sy --noconfirm git openssh ansible sudo base-devel python-pip shadow
#           pip install --break-system-packages ansible-lint
# 
#           useradd -m -u 1000 ansible
#           echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible
# 
#           # Ensure ownership of home directory
#           chown -R ansible:ansible /home/ansible
# 
#           # Install AUR collection as ansible user
#           sudo -u ansible HOME=/home/ansible ansible-galaxy collection install kewlfft.aur
# 
#       - name: Checkout repo
#         uses: actions/checkout@v3
# 
#       - name: Set up vault password
#         run: |
#           mkdir -p /home/ansible
#           echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /home/ansible/.vault_pass.txt
#           chown -R ansible:ansible /home/ansible/.vault_pass.txt
# 
#       - name: Run ansible-lint
#         run: |
#           sudo -u ansible bash -c "
#             export HOME=/home/ansible
#             cd $GITHUB_WORKSPACE
#             ansible-lint ansible/playbook.yml
#           "
# 
#       - name: "Run dry-run for host: ${{ matrix.host }}"
#         run: |
#           sudo -u ansible bash -c "
#             export HOME=/home/ansible
#             cd $GITHUB_WORKSPACE
#             ansible-playbook ansible/playbook.yml \
#               -i localhost, \
#               --connection=local \
#               --vault-password-file /home/ansible/.vault_pass.txt \
#               --check \
#               -e ansible_hostname=${{ matrix.host }}
#           "
